# This file stores configurations for your Shopify app.
client_id = "76cbd3db72a6c05f0df30a6a13640c3e"

scopes = "read_fulfillments,write_fulfillments,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders,write_third_party_fulfillment_orders,read_locations,read_customers,write_customers,read_all_orders,read_content,write_content,read_themes,write_themes,read_orders,write_orders,read_draft_orders,write_draft_orders,read_products,write_products,read_shopify_payments_disputes,read_customers,write_customers,read_shipping,write_publications,write_discounts,read_discounts,read_script_tags,write_script_tags,read_order_edits,write_order_edits"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "navidium-dev-2.myshopify.com"

[pos]
embedded = false

